spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/lunatech_imdb}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      connectionTimeout: ${HIKARI_CONNECTION_TIME_OUT:20000}
      maximumPoolSize: ${HIKARI_MAXIMUM_POOL_SIZE:5}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${APPLICATION_PORT:8080}
