name: Assemble and Test
on: [ push, pull_request ]
jobs:
  assemble_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '16'
      - name: Gradle Wrapper Install
        run: ./gradlew -v
      - name: Assemble
        run: ./gradlew assemble
      - name: Test
        run: ./gradlew test componentTest
